services:
  mysql:
    image: mysql:8.0
    container_name: kerdosbdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "omarleboss"  
      MYSQL_DATABASE: "Calculs"       
    ports:
      - "4306:3306"
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - data:/var/lib/mysql
  
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/data/weaviate'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  data:
  weaviate_data: